title: Vinyl
url: https://AlexisBRENON.github.io/Vinyl/
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [_config-local.yml, README.md, bower.json, examples/latex]
keep_files: [assets/biblio, assets/img/, assets/libs]

gems: [jekyll-coffeescript]

sass:
    sass_dir: _sass
    style: compressed
