title: Vinyl examples
url: https://alexisbrenon.github.io/Vinyl
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [README.md, examples/latex]
keep_files: [assets/biblio, assets/img/, assets/js/libs]

sass:
    sass_dir: _sass
    style: expanded
